import Head from "next/head";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto
          aspernatur, assumenda ea eum laboru m maxime nobis, numquam possimus,
          praesentium quasi sint temporibus. Earum harum ipsam molestias, porro
          quod saepe suscipit.
        </div>
      </main>
    </>
  );
}
